/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import admin.QuanLyTapPhim;
import admin.SuaTapPhim;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import model.BoPhim;
import model.TapPhim;
import services.utils;

/**
 *
 * @author tranv
 */
public class ItemTapPhimAdmin extends javax.swing.JPanel {

    TapPhim tapPhim;
    BoPhim boPhim;

    /**
     * Creates new form ItemTapPhim
     */
    public ItemTapPhimAdmin(TapPhim tapPhim, BoPhim boPhim) {
        initComponents();
        this.tapPhim = tapPhim;
        this.boPhim = boPhim;

        //gán giá trị vào giao diện
        ganGiaTriLenGiaoDien();
    }

    ;

    public void ganGiaTriLenGiaoDien() {
        lbTenTap.setText("" + tapPhim.getStt() + " - " + tapPhim.getTenTap());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTenTap = new javax.swing.JLabel();
        btnXoaTapPhim = new javax.swing.JLabel();
        btnSua = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(32767, 37));

        lbTenTap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTenTap.setForeground(new java.awt.Color(255, 0, 255));
        lbTenTap.setText("Tên tập phim");

        btnXoaTapPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon-delete.png"))); // NOI18N
        btnXoaTapPhim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaTapPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaTapPhimMouseClicked(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon-pencil.png"))); // NOI18N
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTenTap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaTapPhim)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTenTap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnXoaTapPhim)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaTapPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaTapPhimMouseClicked
        // TODO add your handling code here:
        int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa?.", "", JOptionPane.OK_CANCEL_OPTION);
        if (xacNhan == JOptionPane.OK_OPTION) {
            xuLyXoaTapPhim();
        }

    }//GEN-LAST:event_btnXoaTapPhimMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        //mở màn hình sửa tập phim
        SuaTapPhim manHinhThemTapPhim = new SuaTapPhim(tapPhim, boPhim);
        manHinhThemTapPhim.setVisible(true);
        manHinhThemTapPhim.setLocationRelativeTo(null);//nằm giữa màn hình

        //lấy frame cha
        QuanLyTapPhim frame = (QuanLyTapPhim) utils.layFrameCha(ItemTapPhimAdmin.this);
        
        // thêm sự kiện khi đóng màn hình thêm bộ phim
        manHinhThemTapPhim.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // hiện màn hình hiện tại
                frame.setVisible(true);
                frame.layDSTapPhim();
            }
        });

        // ẩn màn hình hiện tại
        frame.setVisible(false);
    }//GEN-LAST:event_btnSuaMouseClicked

    public void xuLyXoaTapPhim() {

        int kqXoa = TapPhim.xoaTapPhim(tapPhim.getId());
        if (kqXoa > 0) {
            QuanLyTapPhim frame = (QuanLyTapPhim) utils.layFrameCha(ItemTapPhimAdmin.this);
            frame.layDSTapPhim();
        } else {
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnXoaTapPhim;
    private javax.swing.JLabel lbTenTap;
    // End of variables declaration//GEN-END:variables
}
