/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import enums.StatusXoaPhim;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.BoPhim;
import admin.QuanLyPhim;
import admin.SuaBoPhim;
import admin.XemTTBoPhim;
import services.utils;

/**
 *
 * @author tranv
 */
public class ItemPhimAdmin extends javax.swing.JPanel {

    BoPhim boPhim;

    /**
     * Creates new form ItemPhim
     */
    public ItemPhimAdmin(BoPhim boPhim) {
        initComponents();
        this.boPhim = boPhim;

        //khởi tạo giao diện
        khoiTao();
    }

    public void khoiTao() {
        //gán giá trị vào các label
        lbTenPhim.setText(boPhim.getTenPhim());
        lbDaoDien.setText(boPhim.getDaoDien());

       //khởi tạo 1 luồng xử lý riêng để tải ảnh
        new Thread(() -> {
             //tạo image icon từ url ảnh poster
            ImageIcon anhPhim = utils.layImageIcon(boPhim.getAnhPoster(), 35, 35);
            lbAnhPhim.setIcon(anhPhim); //gán ảnh vào label ảnh
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAnhPhim = new javax.swing.JLabel();
        lbTenPhim = new javax.swing.JLabel();
        btnXoa = new javax.swing.JLabel();
        btnSua = new javax.swing.JLabel();
        btnXemTT = new javax.swing.JLabel();
        lbDaoDien = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(153, 255, 255));
        setMaximumSize(new java.awt.Dimension(32767, 59));

        lbTenPhim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTenPhim.setForeground(new java.awt.Color(255, 0, 255));
        lbTenPhim.setText("Ten phim 1");

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon-delete.png"))); // NOI18N
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon-pencil.png"))); // NOI18N
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnXemTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon-eye.png"))); // NOI18N
        btnXemTT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXemTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXemTTMouseClicked(evt);
            }
        });

        lbDaoDien.setText("Ten dao dien");

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAnhPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTenPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDaoDien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnXemTT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXemTT)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbTenPhim)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDaoDien))
                        .addComponent(lbAnhPhim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        int xacNhan = JOptionPane.showConfirmDialog(null, "Tất cả tập phim của bộ phim này cũng sẽ bị xóa.","Bạn có chắc chắn muốn xóa?",JOptionPane.OK_CANCEL_OPTION);
        if(xacNhan == JOptionPane.OK_OPTION) {
             xuLyXoaBoPhim();
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        //lấy frame cha
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(ItemPhimAdmin.this);
        
        //mở màn hình sửa bộ phim
        SuaBoPhim manHinhSuaBoPhim = new SuaBoPhim(boPhim);
        manHinhSuaBoPhim.setVisible(true); // cho hiển thị lên
        manHinhSuaBoPhim.setLocationRelativeTo(null); // cho nằm giữa màn hình
        
        // thêm sự kiện khi đóng màn hình
        manHinhSuaBoPhim.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // hiện lại frame cha
                frame.setVisible(true);
                QuanLyPhim.layDSPhim();
            }
        });

        // ẩn frame cha
        frame.setVisible(false);
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXemTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXemTTMouseClicked
        // TODO add your handling code here:
        //lấy frame cha
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(ItemPhimAdmin.this);
        
         //mở màn hình sửa bộ phim
        XemTTBoPhim manHinhXemTTBoPhim = new XemTTBoPhim(boPhim);
        manHinhXemTTBoPhim.setVisible(true); // cho hiển thị lên
        manHinhXemTTBoPhim.setLocationRelativeTo(null); // cho nằm giữa màn hình
        
        // thêm sự kiện khi đóng màn hình
        manHinhXemTTBoPhim.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // hiện lại frame cha
                frame.setVisible(true);
            }
        });

        // ẩn frame cha
        frame.setVisible(false);
        
        
    }//GEN-LAST:event_btnXemTTMouseClicked

    public void xuLyXoaBoPhim() {
        StatusXoaPhim kqXoa = boPhim.xoaPhim();
        if(kqXoa == StatusXoaPhim.SUCCESS) {
            QuanLyPhim.layDSPhim();
        }
        else if(kqXoa == StatusXoaPhim.ERRORR) {
            JOptionPane.showMessageDialog(null, "Xóa phim thất bại.");
        }
        else {
            JOptionPane.showMessageDialog(null, "Xóa phim thành công nhưng xóa tập phim thất bại.");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnXemTT;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAnhPhim;
    private javax.swing.JLabel lbDaoDien;
    private javax.swing.JLabel lbTenPhim;
    // End of variables declaration//GEN-END:variables
}
