/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import services.MySql;

/**
 *
 * @author tranv
 */
public class ItemBinhLuan extends javax.swing.JPanel {

    String idBinhLuan;
    String idUser;
    String noiDung;
    boolean isCurrent;

    /**
     * Creates new form ItemBinhLuan
     */
    public ItemBinhLuan(String idBinhLuan, String idUser, String noiDung, boolean isCurrent) {
        initComponents();
        this.idBinhLuan = idBinhLuan;
        this.idUser = idUser;
        this.noiDung = noiDung;
        this.isCurrent = isCurrent;

        lblNoiDung.setText(noiDung);
        btnDelete.setVisible(isCurrent);
        
        getUser();
    }
    
    public void getUser() {
        
        try {
            ResultSet kq = MySql.queryData(String.format("select * from User where Id = '%s'", idUser));
            if(kq.next()) {
                String ten = kq.getString("HoTen");
                lblTen.setText(ten);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ItemBinhLuan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTen = new javax.swing.JLabel();
        lblNoiDung = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(32767, 54));

        lblTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTen.setForeground(new java.awt.Color(204, 204, 204));
        lblTen.setText("Ten user");

        lblNoiDung.setForeground(new java.awt.Color(255, 255, 255));
        lblNoiDung.setText("jLabel2");

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon-delete.png"))); // NOI18N
        btnDelete.setBorder(null);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addGap(0, 176, Short.MAX_VALUE))
                    .addComponent(lblNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNoiDung)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int xacnhan = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa?");
        if(xacnhan == JOptionPane.OK_OPTION) {
            int kq = MySql.excuteQuery(String.format("delete from BinhLuan where Id = '%s'", idBinhLuan));
            setVisible(false);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel lblNoiDung;
    private javax.swing.JLabel lblTen;
    // End of variables declaration//GEN-END:variables
}
