/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import model.BoPhim;
import services.LocalData;
import services.MySql;
import services.utils;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import panels.ItemBinhLuan;

/**
 *
 * @author tranv
 */
public class ChiTietPhim extends javax.swing.JFrame {

    BoPhim boPhim;
    boolean isLike = false;

    /**
     * Creates new form ChiTietPhim
     */
    public ChiTietPhim(BoPhim boPhim) {
        initComponents();
        this.boPhim = boPhim;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);//chế độ đóng (chỉ đóng màn hình hiện tại)

        //gán giá trị lên giao diện
        ganGiaTri();

        //check yeu thich
        checkYeuThich();
        
        //get binh luan
        getBinhLuan();
    }
    
    public void getBinhLuan() {
        try {
            pnListComment.removeAll();
            String idCurrentUser = LocalData.getData("IdUser");
            ResultSet kq = MySql.queryData(String.format("select * from BinhLuan where IdBoPhim = '%s' order by stt desc", boPhim.getId()));
            while(kq.next()) {
                String Id = kq.getString("Id");
                String IdUser = kq.getString("IdUser");
                String NoiDung = kq.getString("NoiDung");
                
                ItemBinhLuan itemBinhLuan = new ItemBinhLuan(Id, IdUser, NoiDung, IdUser.equals(idCurrentUser));
                pnListComment.add(itemBinhLuan);
            }
            pnListComment.repaint();
            pnListComment.revalidate();
        } catch (SQLException ex) {
            Logger.getLogger(ChiTietPhim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void checkYeuThich() {
        if (utils.kiemTraDangNhap()) {
            try {
                String idBoPhim = boPhim.getId();
                String idUser = LocalData.getData("IdUser");

                ResultSet kq = MySql.queryData(String.format("select * from YeuThich where IdBoPhim = '%s' and IdUser = '%s'", idBoPhim, idUser));
                if (kq.next()) {
                    isLike = true;
                    ImageIcon icon = new ImageIcon(getClass().getResource("/icons/icons-like.png"));
                    btnLike.setIcon(icon);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ChiTietPhim.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    public void ganGiaTri() {
        new Thread(() -> {
            ImageIcon anh = utils.layImageIcon(boPhim.getAnhPoster(), 191, 243);
            lbAnhPhim.setIcon(anh);
        }).start();

        lbTenPhim.setText(boPhim.getTenPhim());
        lbDienVien.setText(boPhim.getDienVien());
        taMoTa.setText(boPhim.getMoTa());
        lbTheLoai.setText("Thể loại: " + boPhim.getTheLoai());
        lbSoTap.setText("Số tập: " + boPhim.getSoTap());
        lbQuocGia.setText("Quốc gia: " + boPhim.getQuocGia());
        lbDaoDien.setText("Đạo diễn: " + boPhim.getDaoDien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbAnhPhim = new javax.swing.JLabel();
        lbTenPhim = new javax.swing.JLabel();
        lbDienVien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMoTa = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        lbTheLoai = new javax.swing.JLabel();
        lbQuocGia = new javax.swing.JLabel();
        lbSoTap = new javax.swing.JLabel();
        lbDaoDien = new javax.swing.JLabel();
        btnXemPhim = new javax.swing.JButton();
        btnLike = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfBinhLuan = new javax.swing.JTextArea();
        btnBinhLuan = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnListComment = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(15, 20, 22));
        jPanel3.setPreferredSize(new java.awt.Dimension(687, 500));

        jPanel4.setBackground(new java.awt.Color(10, 11, 12));

        lbAnhPhim.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        lbAnhPhim.setPreferredSize(new java.awt.Dimension(191, 243));

        lbTenPhim.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbTenPhim.setForeground(new java.awt.Color(208, 193, 7));
        lbTenPhim.setText("Ten phim 1");

        lbDienVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDienVien.setForeground(new java.awt.Color(255, 255, 255));
        lbDienVien.setText("Xiang Xi GuiShi");

        jScrollPane1.setBorder(null);

        taMoTa.setBackground(new java.awt.Color(10, 11, 12));
        taMoTa.setColumns(20);
        taMoTa.setForeground(new java.awt.Color(204, 204, 204));
        taMoTa.setLineWrap(true);
        taMoTa.setRows(5);
        taMoTa.setWrapStyleWord(true);
        taMoTa.setEnabled(false);
        taMoTa.setFocusable(false);
        jScrollPane1.setViewportView(taMoTa);

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        lbTheLoai.setForeground(new java.awt.Color(153, 153, 153));
        lbTheLoai.setText("Thể loại: ngôn tình");

        lbQuocGia.setForeground(new java.awt.Color(153, 153, 153));
        lbQuocGia.setText("Quốc gia: Trung Quốc");

        lbSoTap.setForeground(new java.awt.Color(153, 153, 153));
        lbSoTap.setText("Số tập: 46");

        lbDaoDien.setForeground(new java.awt.Color(153, 153, 153));
        lbDaoDien.setText("Đạo điễn: Thuần Khiết");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAnhPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbQuocGia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                        .addComponent(lbDaoDien)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbTheLoai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbSoTap)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTenPhim)
                                    .addComponent(lbDienVien))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAnhPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbTenPhim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDienVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTheLoai)
                            .addComponent(lbSoTap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQuocGia)
                            .addComponent(lbDaoDien))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnXemPhim.setBackground(new java.awt.Color(255, 0, 255));
        btnXemPhim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXemPhim.setForeground(new java.awt.Color(102, 255, 0));
        btnXemPhim.setText("Xem phim");
        btnXemPhim.setFocusPainted(false);
        btnXemPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemPhimActionPerformed(evt);
            }
        });

        btnLike.setBackground(new java.awt.Color(0, 0, 0));
        btnLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-nolike.png"))); // NOI18N
        btnLike.setBorder(null);
        btnLike.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeActionPerformed(evt);
            }
        });

        tfBinhLuan.setColumns(20);
        tfBinhLuan.setRows(5);
        jScrollPane3.setViewportView(tfBinhLuan);

        btnBinhLuan.setText("Bình luận");
        btnBinhLuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinhLuanActionPerformed(evt);
            }
        });

        jScrollPane4.setBorder(null);

        pnListComment.setBackground(new java.awt.Color(0, 0, 0));
        pnListComment.setLayout(new javax.swing.BoxLayout(pnListComment, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane4.setViewportView(pnListComment);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnXemPhim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLike))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBinhLuan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXemPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLike))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBinhLuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemPhimActionPerformed
        // TODO add your handling code here:

        //mở màn hình xem phim
        XemPhim manHinhXemPhim = new XemPhim(boPhim);
        manHinhXemPhim.setVisible(true);
        manHinhXemPhim.setLocationRelativeTo(null);

        //sự kiện đóng màn hình xem phim
        manHinhXemPhim.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                setVisible(true); // hiện màn hình hiện tại lên
            }

        });

        //ẩn màn hình hiện tại
        setVisible(false);
    }//GEN-LAST:event_btnXemPhimActionPerformed

    private void btnLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeActionPerformed
        // TODO add your handling code here:
        if (isLike) {
            boYeuThich();

        } else {
            themYeuThich();
        }

    }//GEN-LAST:event_btnLikeActionPerformed

    private void btnBinhLuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinhLuanActionPerformed
        // TODO add your handling code here:
        if (utils.kiemTraDangNhap()) {
            themBinhLuan();
        } else {
            setVisible(false);
            DangNhap manHinhDangNhap = new DangNhap();
            manHinhDangNhap.setVisible(true); // cho hiển thị lên
            manHinhDangNhap.setLocationRelativeTo(null); // cho nằm giữa màn hình
            manHinhDangNhap.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    setVisible(true);
                    if (DangNhap.isLogin) {
                        themBinhLuan();
                        return;

                    }

                }
            });
        }
    }//GEN-LAST:event_btnBinhLuanActionPerformed

    public void themBinhLuan() {
        String noiDung = tfBinhLuan.getText();
        String idUser = LocalData.getData("IdUser");
        if (!noiDung.isEmpty()) {
            
            int kq = MySql.excuteQuery(String.format("insert into BinhLuan (Id, IdBoPhim,IdUser,NoiDung) values ('%s','%s','%s','%s')", 
                    utils.randomId(),boPhim.getId(),idUser,noiDung));
            if(kq < 0) {
                JOptionPane.showMessageDialog(null, "Bình luận thất bại!"); 
            }
            else {
                tfBinhLuan.setText("");
                getBinhLuan();
                
            }
            
        }
    }

    public void themYeuThich() {
        if (utils.kiemTraDangNhap()) {
            String idBoPhim = boPhim.getId();
            String idUser = LocalData.getData("IdUser");

            int kq = MySql.excuteQuery(String.format("insert into YeuThich (Id,IdBoPhim, IdUser) values ('%s','%s','%s')", utils.randomId(), idBoPhim, idUser));
            if (kq < 0) {

            } else {
                ImageIcon icon = new ImageIcon(getClass().getResource("/icons/icons-like.png"));
                btnLike.setIcon(icon);
                isLike = true;
            }

        } else {
            setVisible(false);
            DangNhap manHinhDangNhap = new DangNhap();
            manHinhDangNhap.setVisible(true); // cho hiển thị lên
            manHinhDangNhap.setLocationRelativeTo(null); // cho nằm giữa màn hình
            manHinhDangNhap.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    setVisible(true);
                    if (DangNhap.isLogin) {
                        themYeuThich();
                        return;

                    }

                }
            });
        }
    }

    public void boYeuThich() {
        String idBoPhim = boPhim.getId();
        String idUser = LocalData.getData("IdUser");

        int kq = MySql.excuteQuery(String.format("delete from YeuThich where IdBoPhim = '%s' and IdUser = '%s'", idBoPhim, idUser));
        if (kq < 0) {

        } else {
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/icons-nolike.png"));
            btnLike.setIcon(icon);
            isLike = false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBinhLuan;
    private javax.swing.JButton btnLike;
    private javax.swing.JButton btnXemPhim;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAnhPhim;
    private javax.swing.JLabel lbDaoDien;
    private javax.swing.JLabel lbDienVien;
    private javax.swing.JLabel lbQuocGia;
    private javax.swing.JLabel lbSoTap;
    private javax.swing.JLabel lbTenPhim;
    private javax.swing.JLabel lbTheLoai;
    private javax.swing.JPanel pnListComment;
    private javax.swing.JTextArea taMoTa;
    private javax.swing.JTextArea tfBinhLuan;
    // End of variables declaration//GEN-END:variables
}
