/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import model.BoPhim;
import panels.ItemPhim;
import services.LocalData;
import services.MySql;

/**
 *
 * @author tranv
 */
public class YeuThich extends javax.swing.JFrame {

    /**
     * Creates new form YeuThich
     */
    public YeuThich() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        getListVideo();
    }

    public void getListVideo() {
        String idUser = LocalData.getData("IdUser");
        if (idUser != null) {
            try {
                ResultSet kq = MySql.queryData(String.format("select * from YeuThich where IdUser = '%s'", idUser));

                ArrayList<BoPhim> dsBoPhim = new ArrayList<>();
                while (kq.next()) {
                    String idBoPhim = kq.getString("IdBoPhim");
                    ResultSet kqBoPhim = MySql.queryData(String.format("select * from BoPhim where Id = '%s'", idBoPhim));
                    if (kqBoPhim.next()) {
                        BoPhim bp = BoPhim.chuyenDoi_ResultSet(kqBoPhim);
                        dsBoPhim.add(bp);
                    }
                }

                //hien thi
                pnListVideo.removeAll();
                int dong = (dsBoPhim.size() + 1) / 2;
                GridLayout gridLayout = new GridLayout(dong, 2);
                pnListVideo.setLayout(gridLayout);

                for (BoPhim boPhim : dsBoPhim) {
                    JPanel pnTapPhim = new ItemPhim(boPhim);//khởi tạo panel tập phim
                    pnListVideo.add(pnTapPhim);//thêm panel tập phim vào giao diện
                }
                //reset giao diện
                pnListVideo.revalidate();
                pnListVideo.repaint();

            } catch (SQLException ex) {
                Logger.getLogger(YeuThich.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnListVideo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách yêu thích");

        jScrollPane1.setBorder(null);

        pnListVideo.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(pnListVideo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnListVideo;
    // End of variables declaration//GEN-END:variables
}
