/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.BoPhim;
import model.TapPhim;
import services.MySql;
import services.utils;

/**
 *
 * @author tranv
 */
public class SuaTapPhim extends javax.swing.JFrame {
    
    TapPhim tapPhim;
    BoPhim boPhim;

    /**
     * Creates new form ThemTapPhim
     */
    public SuaTapPhim(TapPhim tapPhim, BoPhim boPhim) {
        initComponents();
        this.tapPhim = tapPhim;
        this.boPhim = boPhim;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);//chế độ đóng (chỉ đóng màn hình hiện tại)

        //gán giá trị lên giao diện
        ganGiaTri();
        
    }
    
    public void ganGiaTri() {
        //gán giá trị cho combobox
        ganGiaTriCombobox();

        //gán giá trị lên textField
        tfTenTap.setText(tapPhim.getTenTap());
        tfUrlVideo.setText(tapPhim.getUrlVideo());
    }
    
    public void ganGiaTriCombobox() {
        int soTap = boPhim.getSoTap();
        ArrayList<String> itemsList = new ArrayList<>();
        for (int i = 1; i <= soTap; i++) {
            itemsList.add("" + i);
        }
        String[] items = itemsList.toArray(new String[0]);

        // Tạo một ComboBoxModel từ mảng items
        ComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(items);
        cbTap.setModel(comboBoxModel);
        cbTap.setSelectedIndex(tapPhim.getStt() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTenTap = new javax.swing.JTextField();
        cbTap = new javax.swing.JComboBox<>();
        btnLuu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfUrlVideo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sửa tập phim");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tên tập:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tập:");

        tfTenTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenTapActionPerformed(evt);
            }
        });

        cbTap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("URL Video:");

        tfUrlVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUrlVideoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLuu)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTenTap, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfUrlVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTenTap)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfUrlVideo)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLuu)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        xuLySuaTapPhim();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tfTenTapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenTapActionPerformed
        // TODO add your handling code here:
        xuLySuaTapPhim();
    }//GEN-LAST:event_tfTenTapActionPerformed

    private void tfUrlVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUrlVideoActionPerformed
        // TODO add your handling code here:
        xuLySuaTapPhim();
    }//GEN-LAST:event_tfUrlVideoActionPerformed
    
    public void xuLySuaTapPhim() {
        //lấy dữ liệu nhập vào
        String tenTap = tfTenTap.getText();
        int tap = cbTap.getSelectedIndex() + 1;
        String urlVideo = tfUrlVideo.getText();
        
        tapPhim.setTenTap(tenTap);
        tapPhim.setStt(tap);
        tapPhim.setUrlVideo(urlVideo);
        
        //kiểm tra dữ liệu nhập vào
        if (tenTap.isEmpty() || urlVideo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đây đủ thông tin");
            return; //Dừng xử lý
        }
        
        //check tập phim
        if (TapPhim.checkTapPhimSua(tenTap, tap, boPhim.getId())) {
            JOptionPane.showMessageDialog(null, "Tập phim đã tồn tại.");
            return; //Dừng xử lý
        }
        
        //Sửa tập phim
        boolean kqSua = tapPhim.suaTapPhim();
        if(kqSua) {
            JOptionPane.showMessageDialog(null, "Đã sửa.");
        }
        else {
            JOptionPane.showMessageDialog(null, "Sửa thất bại.");
        }
        
        
    }
    
    public void resetForm() {
        tfTenTap.setText("");
        tfUrlVideo.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbTap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfTenTap;
    private javax.swing.JTextField tfUrlVideo;
    // End of variables declaration//GEN-END:variables
}
